# Configuracao do RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer=OFF
logging.level.org.springframework.amqp.rabbit.connection.CachingConnectionFactory=WARN
logging.level.org.springframework.amqp=OFF

### O fdp que tiver coragem de apagar essa config vai pagar a conta da aws beleza
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000
###

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.datasource.url=jdbc:mysql://localhost:3306/agiliz?serverTimezone=America/Sao_Paulo
spring.datasource.username=root
zone.id=America/Sao_Paulo
feign.client.enabled=true
spring.jpa.properties.hibernate.format_sql=true
api_url=http://localhost:8081
firebase.config.file.location=src/main/resources/agiliz-logistics-6efd2-firebase-adminsdk-40nmj-7a34820fe8.json
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.kafka.clients.NetworkClient=ERROR
logging.level.org.springframework.kafka=ERROR
ms.roteirizacao.url=http://localhost:8081
spring.datasource.password=churrasco2015
spring.mvc.servlet.path=/agiliz
google.api.key=AIzaSyCJ8dDiCztHKynbmj7ZkZMBfY_29LOuFEU
spring.task.scheduling.enabled=true
spring.scheduling.enableCronSecondPrecision=true
spring.jackson.date-format=com.fasterxml.jackson.databind.util.StdDateFormat
spring.jackson.deserialization.fail-on-unknown-properties=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.export.prometheus.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedrohsilva54ed209@gmail.com
spring.mail.password=ynpcudgzrumlhvvh
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
api.url=http://localhost:3000/
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
server.error.include-message=always
server.error.include-binding-errors=always
jwt.validity=3600000
jwt.secret=cPqikLBo7pdyw0LOuYgQYq5mRYfWlv7tsmWguN39wONXZ7GvmUZKZUwJLsRTA7GrS5JYTHvWEsFIlxNdUxZAC7oE3l8N1OIZn26SQqGx2Vi26zPmBeFgblF4WzH8GpnzmI4kGf7AD4rIl14I0mQbT3VdSakxKpSRiFV6UWPSwNjKMTazcPjhzKBhqGQqcxnyrR22Y3ePI6C3eMb4MVvznQ27eXXYrHf23cncHnPSGA
application.title=Agiliz Logistics API
application.version=1.0.0